### ISSUE TITLE
Fork Strap

### ISSUE THREAD

**Issue by flatiron32** [jodylent/project-show-animal#3]
https://github.com/jodylent/project-show-animal/blob/8aa5a191fc71dc016023017d7cd4f7cda4fbdbe7/new_mac.sh#L78-L84

I think this might be better served by forking strap (or trying to make a PR). In the fork the script to be parameterized.

**Comment by jodylent** [comment]
Looks like Strap will not support SSH (HTTPS only) per https://github.com/MikeMcQuaid/strap/issues/17 . 

Since everything else has been addressed, I'm leaving the two 'sed s/https/ssh/g' lines as-is and closing the issue.
