### ISSUE TITLE
Overly opinionated git config?

### ISSUE THREAD

**Issue by flatiron32** [jodylent/project-show-animal#9]
I don't disagree with the show animal git config, but it might be best to make it optional and at minimum document what is happening.

The manipulation of strap though seems fine, BTW. Are they tightly (strap-hack and git config) coupled?

**Comment by jodylent** [comment]
Strap uses HTTPS auth by default, which annoys me because every token is one-source-use only, requiring a new token per laptop. I much prefer just bringing my ssh keys along with me.
